package org.wavemelon.awesomeareas;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;
import org.wavemelon.awesomeareas.core.area.Area;
import org.wavemelon.awesomeareas.core.area.AreaType;
import org.wavemelon.awesomeareas.core.boundary.BlockGridBoundary;
import org.wavemelon.awesomeareas.core.boundary.Boundary;
import org.wavemelon.awesomeareas.core.boundary.BoxBoundary;
import org.wavemelon.awesomeareas.core.boundary.PolygonBoundary;
import org.wavemelon.awesomeareas.core.storage.AreaManager;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

public class SaveMigrationTest {

    @Test
    public void migrateAllSaves() throws Exception {
        File savesDir = new File("run/saves");
        if (!savesDir.exists()) return;

        File[] worldDirs = savesDir.listFiles(File::isDirectory);
        if (worldDirs == null) return;

        for (File worldDir : worldDirs) {
            File jsonFile = new File(worldDir, "awesomeareas/awesomeareas.json");
            if (!jsonFile.exists()) continue;

            System.out.println("Processing save: " + jsonFile.getAbsolutePath());
            String jsonContent = Files.readString(jsonFile.toPath());
            JsonObject root = JsonParser.parseString(jsonContent).getAsJsonObject();

            if (!root.has("areas")) continue;
            JsonArray areasArr = root.getAsJsonArray("areas");

            List<Area> loadedAreas = new ArrayList<>();
            for (JsonElement el : areasArr) {
                JsonObject obj = el.getAsJsonObject();
                UUID id = UUID.fromString(obj.get("id").getAsString());
                String name = obj.get("name").getAsString();
                AreaType type = AreaType.valueOf(obj.get("type").getAsString());

                Boundary boundary = null;
                if (obj.has("boundary")) {
                    boundary = AreaManager.deserializeBoundary(obj.getAsJsonObject("boundary"));
                }

                Area area = new Area(id, name, type, boundary != null ? boundary : new BoxBoundary(0, 0, 0, 0));
                if (obj.has("customTypeDisplayName")) {
                    area.setCustomTypeDisplayName(obj.get("customTypeDisplayName").getAsString());
                }
                if (obj.has("parentId")) {
                    area.setParentId(UUID.fromString(obj.get("parentId").getAsString()));
                }
                if (obj.has("leaderUuid")) {
                    UUID leaderUuid = UUID.fromString(obj.get("leaderUuid").getAsString());
                    String leaderName = obj.has("leaderName") ? obj.get("leaderName").getAsString() : "Unknown";
                    area.setLeader(leaderUuid, leaderName);
                }
                if (obj.has("capitalAreaId")) {
                    area.setCapitalAreaId(UUID.fromString(obj.get("capitalAreaId").getAsString()));
                }
                if (obj.has("color")) {
                    area.setColor(obj.get("color").getAsInt());
                }
                if (obj.has("autoGenerated")) {
                    area.setAutoGenerated(obj.get("autoGenerated").getAsBoolean());
                }
                if (obj.has("createdTimestamp")) {
                    area.setCreatedTime(obj.get("createdTimestamp").getAsLong());
                }
                if (obj.has("villagerCount")) {
                    area.setVillagerCount(obj.get("villagerCount").getAsInt());
                }
                if (obj.has("pastNames")) {
                    for (JsonElement p : obj.getAsJsonArray("pastNames")) {
                        area.addPastName(p.getAsString());
                    }
                }
                loadedAreas.add(area);
            }

            // Convert all boundaries to BlockGridBoundary and resolve any peer overlaps
            // Group by peer level/type
            Map<AreaType, List<Area>> byType = new HashMap<>();
            for (Area a : loadedAreas) {
                byType.computeIfAbsent(a.getType(), k -> new ArrayList<>()).add(a);
            }

            for (Map.Entry<AreaType, List<Area>> entry : byType.entrySet()) {
                List<Area> peerAreas = entry.getValue();
                if (peerAreas.size() <= 1) {
                    for (Area a : peerAreas) {
                        if (!(a.getBoundary() instanceof BlockGridBoundary)) {
                            a.setBoundary(convertToBlockGrid(a.getBoundary()));
                        }
                    }
                    continue;
                }

                // Check for overlaps between peers
                boolean hadOverlap = false;
                for (int i = 0; i < peerAreas.size(); i++) {
                    for (int j = i + 1; j < peerAreas.size(); j++) {
                        if (peerAreas.get(i).getBoundary().intersects(peerAreas.get(j).getBoundary())) {
                            hadOverlap = true;
                            break;
                        }
                    }
                    if (hadOverlap) break;
                }

                if (hadOverlap) {
                    System.out.println("Resolving peer overlap among " + entry.getKey() + " areas in " + worldDir.getName());
                    // Rasterize each peer area into set of packed block coordinates
                    Map<Area, Set<Long>> blockSets = new HashMap<>();
                    for (Area a : peerAreas) {
                        blockSets.put(a, rasterizeBlocks(a.getBoundary()));
                    }

                    // For any overlapping block, assign it to the area whose center is closer
                    for (int i = 0; i < peerAreas.size(); i++) {
                        Area a1 = peerAreas.get(i);
                        Set<Long> set1 = blockSets.get(a1);
                        double c1x = a1.getBoundary().getCenterX();
                        double c1z = a1.getBoundary().getCenterZ();

                        for (int j = i + 1; j < peerAreas.size(); j++) {
                            Area a2 = peerAreas.get(j);
                            Set<Long> set2 = blockSets.get(a2);
                            double c2x = a2.getBoundary().getCenterX();
                            double c2z = a2.getBoundary().getCenterZ();

                            // Find intersection
                            Set<Long> intersection = new HashSet<>(set1);
                            intersection.retainAll(set2);

                            for (long packed : intersection) {
                                int bx = (int) (packed >> 32);
                                int bz = (int) packed;
                                double d1 = (bx - c1x) * (bx - c1x) + (bz - c1z) * (bz - c1z);
                                double d2 = (bx - c2x) * (bx - c2x) + (bz - c2z) * (bz - c2z);

                                if (d1 <= d2) {
                                    set2.remove(packed);
                                } else {
                                    set1.remove(packed);
                                }
                            }
                        }
                    }

                    // Rebuild BlockGridBoundary from resolved non-overlapping block sets
                    for (Area a : peerAreas) {
                        Set<Long> blocks = blockSets.get(a);
                        BlockGridBoundary resolvedBgb = BlockGridBoundary.fromBlocks(blocks);
                        a.setBoundary(resolvedBgb);
                    }
                } else {
                    for (Area a : peerAreas) {
                        if (!(a.getBoundary() instanceof BlockGridBoundary)) {
                            a.setBoundary(convertToBlockGrid(a.getBoundary()));
                        }
                    }
                }
            }

            // Create AreaManager and populate
            AreaManager manager = new AreaManager();
            for (Area a : loadedAreas) {
                manager.addArea(a);
            }

            // Also copy homes if present
            if (root.has("homes")) {
                for (JsonElement el : root.getAsJsonArray("homes")) {
                    JsonObject hObj = el.getAsJsonObject();
                    manager.setHome(new org.wavemelon.awesomeareas.core.home.Home(
                            UUID.fromString(hObj.get("id").getAsString()),
                            UUID.fromString(hObj.get("ownerUuid").getAsString()),
                            hObj.get("ownerName").getAsString(),
                            hObj.get("x").getAsInt(),
                            hObj.get("y").getAsInt(),
                            hObj.get("z").getAsInt(),
                            hObj.get("dimension").getAsString(),
                            hObj.has("villager") && hObj.get("villager").getAsBoolean()
                    ));
                }
            }

            // Write back updated JSON
            String updatedJson = manager.exportToJsonString();
            Files.writeString(jsonFile.toPath(), updatedJson);
            System.out.println("Successfully migrated: " + jsonFile.getAbsolutePath());
        }
    }

    private static BlockGridBoundary convertToBlockGrid(Boundary b) {
        if (b instanceof BlockGridBoundary bgb) return bgb;
        if (b instanceof BoxBoundary box) {
            return new BlockGridBoundary(List.of(box));
        }
        if (b instanceof PolygonBoundary pb) {
            return pb.getGridBoundary();
        }
        return new BlockGridBoundary(List.of(new BoxBoundary(b.getMinX(), b.getMinZ(), b.getMaxX(), b.getMaxZ())));
    }

    private static Set<Long> rasterizeBlocks(Boundary b) {
        Set<Long> set = new HashSet<>();
        for (int x = b.getMinX(); x <= b.getMaxX(); x++) {
            for (int z = b.getMinZ(); z <= b.getMaxZ(); z++) {
                if (b.contains(x, z)) {
                    set.add(((long) x << 32) | (z & 0xFFFFFFFFL));
                }
            }
        }
        return set;
    }
}
