package org.wavemelon.awesomeareas.core.area;

import org.wavemelon.awesomeareas.core.boundary.Boundary;
import org.wavemelon.awesomeareas.core.history.AreaHistoryEntry;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Core territorial unit representing a geographic and administrative entity.
 */
public class Area {
    private final UUID id;
    private String name;
    private AreaType type;
    private String customTypeDisplayName;
    private Boundary boundary;
    private UUID parentId;
    private UUID leaderUuid;
    private String leaderName;
    private UUID capitalAreaId;
    private int color;
    private boolean autoGenerated;
    private long createdTime;
    private int villagerCount = 0;

    private final List<String> pastNames = new ArrayList<>();
    private final List<AreaHistoryEntry> history = new ArrayList<>();

    public Area(UUID id, String name, AreaType type, Boundary boundary) {
        this.id = Objects.requireNonNull(id, "Area ID cannot be null");
        this.type = Objects.requireNonNull(type, "AreaType cannot be null");
        this.boundary = Objects.requireNonNull(boundary, "Boundary cannot be null");
        this.color = type.getDefaultColor();
        this.createdTime = System.currentTimeMillis();
        setName(name);
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = type.formatAreaName(name, customTypeDisplayName);
    }

    public void rename(String newName, String actorName, String inGameDate) {
        String oldName = this.name;
        String formattedNew = type.formatAreaName(newName, customTypeDisplayName);
        if (!oldName.equals(formattedNew)) {
            addPastName(oldName);
            addHistoryEntry(new AreaHistoryEntry(
                    System.currentTimeMillis(),
                    inGameDate,
                    "RENAMED",
                    "Renamed from '" + oldName + "' to '" + formattedNew + "'",
                    actorName,
                    this.boundary
            ));
            this.name = formattedNew;
        }
    }

    public void updateBoundary(Boundary newBoundary, String actorName, String inGameDate) {
        if (newBoundary != null && !newBoundary.equals(this.boundary)) {
            Boundary oldBoundary = this.boundary;
            addHistoryEntry(new AreaHistoryEntry(
                    System.currentTimeMillis(),
                    inGameDate,
                    "BOUNDARY_UPDATE",
                    "Border updated from [" + oldBoundary.getMinX() + ", " + oldBoundary.getMinZ() + "] to [" + newBoundary.getMinX() + ", " + newBoundary.getMinZ() + "]",
                    actorName,
                    oldBoundary
            ));
            this.boundary = newBoundary;
        }
    }

    public AreaType getType() {
        return type;
    }

    public void setType(AreaType type) {
        this.type = Objects.requireNonNull(type, "AreaType cannot be null");
    }

    public String getCustomTypeDisplayName() {
        return customTypeDisplayName;
    }

    public void setCustomTypeDisplayName(String customTypeDisplayName) {
        this.customTypeDisplayName = customTypeDisplayName;
        setName(this.name);
    }

    public String getEffectiveTypeDisplayName() {
        return (customTypeDisplayName != null && !customTypeDisplayName.isBlank())
                ? customTypeDisplayName
                : type.getDefaultDisplayName();
    }

    public Boundary getBoundary() {
        return boundary;
    }

    public void setBoundary(Boundary boundary) {
        this.boundary = Objects.requireNonNull(boundary, "Boundary cannot be null");
    }

    public UUID getParentId() {
        return parentId;
    }

    public void setParentId(UUID parentId) {
        this.parentId = parentId;
    }

    public UUID getLeaderUuid() {
        return leaderUuid;
    }

    public String getLeaderName() {
        return leaderName;
    }

    public void setLeader(UUID leaderUuid, String leaderName) {
        this.leaderUuid = leaderUuid;
        this.leaderName = leaderName;
    }

    public UUID getCapitalAreaId() {
        return capitalAreaId;
    }

    public void setCapitalAreaId(UUID capitalAreaId) {
        this.capitalAreaId = capitalAreaId;
    }

    public int getColor() {
        return color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public long getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(long createdTime) {
        this.createdTime = createdTime;
    }

    public List<String> getPastNames() {
        return Collections.unmodifiableList(pastNames);
    }

    public void addPastName(String pastName) {
        if (pastName != null && !pastName.isBlank() && !pastNames.contains(pastName)) {
            pastNames.add(pastName);
        }
    }

    public List<AreaHistoryEntry> getHistory() {
        return Collections.unmodifiableList(history);
    }

    public void addHistoryEntry(AreaHistoryEntry entry) {
        if (entry != null) {
            history.add(entry);
        }
    }

    public int getVillagerCount() {
        return villagerCount;
    }

    public void setVillagerCount(int villagerCount) {
        this.villagerCount = Math.max(0, villagerCount);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Area area = (Area) o;
        return Objects.equals(id, area.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
